/*
 MIT
 @constructor
*/
(function(u,A){var E=u.InSkin||(u.InSkin={}),x=E.PublisherCode||(E.PublisherCode={}),F=x.LIB||(x.LIB={}),G=x.tests||(x.tests={}),h,i=x.kwFiltersBase||(x.kwFiltersBase={}),H=x.kwLists||(x.kwLists=[]),v=u.document;(function(){h={};h.extend=function(d){d=d||{};for(var b=1;b<arguments.length;b++){var a=arguments[b];if(a)for(var c in a)if(typeof a[c]=="object"){if(typeof d[c]!="object")d[c]={};h.extend(d[c],a[c])}else d[c]=a[c]}return d};h.getURLParams=function(){try{for(var d={},b=u.location.search.substring(1).split("&"),
a=0;a<b.length;a++)if(b[a]){var c=b[a].split("=");d[c[0]]=c[1]?decodeURIComponent(c[1]):""}return d}catch(f){}return{}};h.getScriptParams=function(d,b){b||(b="&");for(var a=A.document.getElementsByTagName("script"),c,f=0;f<a.length;f++)if(a[f].getAttribute("data-ism-processed")!="true")if(c=a[f].src.match(d)){a[f].setAttribute("data-ism-processed","true");a={};if(c.length==3){b=c[1];c=c[2]}else c=c[1];c=c.split(b);for(f=0;f<c.length;f++)if(c[f]!=""){var e=c[f].split("=");a[e[0]]=e[1]?decodeURIComponent(e[1]):
""}return a}return null};h.buildQueryString=function(d,b){var a=[],c;for(c in d){var f=d[c];switch(Object.prototype.toString.call(f)){case "[object Array]":for(var e=0;e<f.length;e++)a.push(c+"="+encodeURIComponent(f[e]));break;case "[object Object]":e=!b?c+".":"";for(var g in f)a.push(e+g+"="+encodeURIComponent(f[g]));break;case "[object Boolean]":a.push(c+"="+f.toString());break;default:a.push(c+"="+encodeURIComponent(f))}}return a.join("&")};h.post=function(d){function b(f){if(!c){c=true;if(d.callback){if(d.json)f=
JSON.parse(f);d.callback(f)}}}var a=new XMLHttpRequest;a.open("POST",d.url,!!d.async);d.json?a.setRequestHeader("Content-Type","application/json; charset=UTF-8"):a.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");a.onreadystatechange=function(){if(a.readyState==4)a.status==200?b(a.responseText):b(null)};var c=false;d.timeout&&setTimeout(function(){b()},d.timeout);a.send(d.json?JSON.stringify(d.data):this.buildQueryString(d.data,d.flatten))};h.jsonp=function(d){function b(j){if(!g){g=
true;f&&f.parentNode.removeChild(f);d.noCleanup||delete c[a];d.callback&&d.callback(j)}}var a=d.callbackName||"ism_jsonp_"+h.random(),c=d.window||u,f,e=d.url;e+=(e.indexOf("?")>=0?"&":"?")+"callback="+a;if(d.data)e+="&"+this.buildQueryString(d.data,d.flatten);var g=false;d.timeout&&setTimeout(function(){b()},d.timeout);c[a]=b;f=h.loadJS(e,c,d.async)};h.loadJS=function(d,b,a,c,f,e){function g(){if(!j){j=true;c()}}b||(b=u);f&&c&&setTimeout(g,f);if(!a&&b.document.readyState=="loading"){b.document.write('<script src="'+
d+'"><\/script>');if(c){e=e||"ism_callback_"+h.random();b[e]=function(){g();delete b[e]};b.document.write("<script>"+e+"();<\/script>")}}else{a=b.document.createElement("script");a.setAttribute("type","text/javascript");a.setAttribute("src",d);if(c)a.onload=a.onerror=g;if(d=b.document.getElementsByTagName("head")[0]){d.appendChild(a);return a}}var j=false};h.runJS=function(d,b){if(b.document.readyState=="loading")b.document.write(d);else{var a=d.match(/^\s*<script[^>]+src\s*=\s*("|')(.+)\1[^>]*>/i);
a?h.loadJS(a[2],b,true):eval(d.replace(/^\s*<script[^>]*>|<\/script>\s*$/ig,""))}};h.loadCSS=function(d,b){b||(b=v);var a=b.createElement("link");a.setAttribute("type","text/css");a.setAttribute("rel","stylesheet");a.setAttribute("href",d);var c=b.getElementsByTagName("head")[0];c&&c.appendChild(a)};h.getFrameDoc=function(d,b){b||(b=v);if(typeof d=="string")d=b.getElementById(d);try{if(d)return d.contentDocument?d.contentDocument:d.contentWindow?d.contentWindow.document:d.document}catch(a){}return null};
h.getPageKeywords=function(d){if(d==undefined)d="meta-";for(var b=[],a=v.getElementsByTagName("meta"),c=0;c<a.length;c++)if(a[c].name&&a[c].name.toLowerCase()=="keywords")if(a[c].content)for(var f=a[c].content.split(","),e=0;e<f.length;e++){var g=f[e].toLowerCase().replace(/[^a-z0-9]/g,"");g.length>1&&b.push(d+g)}return b};h.getURLPathKeywords=function(d){for(var b=[],a=u.location.pathname.split("/"),c="url",f=1,e=0;e<d&&f<a.length;){c+="-"+a[f];b.push(c);f++;e++}return b};h.ensureBooleans=function(d,
b){for(var a,c=0;c<b.length;c++){a=b[c];if(typeof d[a]!="undefined")d[a]=String(d[a]).toLowerCase()=="true"?true:false}};h.ensureIntegers=function(d,b){for(var a,c=0;c<b.length;c++){a=b[c];if(typeof d[a]!="undefined")d[a]=parseInt(d[a])}};h.random=function(){return Math.floor(Math.random()*1E17)};h.extendCSV=function(d,b){d||(d="");return d+(d.length?",":"")+b};h.setCookie=function(d,b,a,c,f,e){if(a){var g=new Date;g.setTime(g.getTime()+a*1E3);a=g}d=d+"="+escape(b)+(a?"; expires="+a.toGMTString():
"")+(c?"; path="+c:"")+(f?"; domain="+f:"")+(e?"; secure":"");v.cookie=d};h.getCookie=function(d){var b=v.cookie;d=d+"=";var a=b.indexOf("; "+d);if(a==-1){a=b.indexOf(d);if(a!=0)return null}else a+=2;var c=v.cookie.indexOf(";",a);if(c==-1)c=b.length;return unescape(b.substring(a+d.length,c))};h.delCookie=function(d,b,a){if(this.getCookie(d))v.cookie=d+"="+(b?"; path="+b:"")+(a?"; domain="+a:"")+"; expires=Thu, 01-Jan-70 00:00:01 GMT"};h.storageSet=function(d,b,a){if(a)b.__expires=(new Date).getTime()+
a*1E3;localStorage.setItem(d,JSON.stringify(b));h.delCookie(d,"/")};h.storageGet=function(d){d=(d=localStorage.getItem(d)||h.getCookie(d))?JSON.parse(d):{};if(d.__expires)if(d.__expires<(new Date).getTime())d={};else delete d.__expires;return d};h.storageDel=function(d){localStorage.removeItem(d);h.delCookie(d,"/")};h.setISAPCookies=function(d){var b={Session:1800,Persistent:31536E3};try{for(var a in b){var c="ISAP"+a,f=d[a+"Cookies"];if(f)h.storageSet(c,h.extend(h.storageGet(c),f),b[a]);else f===
null&&h.storageDel(c)}}catch(e){}};h.getISAPCookies=function(){try{var d=h.storageGet("ISAPSession"),b=h.storageGet("ISAPPersistent"),a=h.extend({},d,b);d=[];for(var c in a)d.push(c+"=="+a[c]);return d.length?{vstrCookieData:d.join("&&")}:{}}catch(f){}};h.loadURL=function(d,b){var a=new Image;if(b)a.onload=b;a.src=d};h.semvercmp=function(d,b){for(var a=d.split("."),c=b.split("."),f=0;f<3;f++){var e=parseInt(a[f]),g=parseInt(c[f]);if(e>g)return 1;if(g>e)return-1;if(!isNaN(e)&&isNaN(g))return 1;if(isNaN(e)&&
!isNaN(g))return-1}return 0};h.bluekaiGet=function(d,b,a){h.loadJS("https://tags.bluekai.com/site/39716?ret=js&limit=1",b,a,function(){var c=[];if(b.bk_results&&b.bk_results.campaigns)for(var f=0;f<b.bk_results.campaigns.length;f++)c.push(b.bk_results.campaigns[f].campaign);d(c)},3E3)};h.bluekaiSet=function(d){u.bk_async=function(){for(var b in d)u.bk_addPageCtx(b,d[b]);u.BKTAG.doTag(38862,4)};h.loadJS("https://tags.bkrtx.com/js/bk-coretag.js",u,true)};h.saveFlightIdViewTime=function(d){var b=Math.round((new Date).getTime()/
1E3),a=JSON.parse(h.getCookie("MFADFlightViewTimes")||"{}");a[d]=a[d]||[];a[d].push(b);for(var c in a){a[c]=a[c].filter(function(f){return f+5184E3>b});a[c].length||delete a[c]}h.setCookie("MFADFlightViewTimes",JSON.stringify(a),0,"/")};h.loadInIframe=function(d){d="<html><head></head><body>"+d+"</body></html>";var b=v.createElement("iframe");b.style.position="fixed";b.style.height="1px";b.style.width="1px";b.style.left="-10px";b.style.top="-10px";v.body.appendChild(b);b.contentWindow.document.open("text/html",
"replace");b.contentWindow.document.write(d);b.contentWindow.document.close()};h.embedUserMatchingIframe=function(){var d=v.createElement("iframe");d.width=d.height=d.frameborder=0;d.scrolling="no";d.style.display="none";var b="https://mfad.inskinad.com/udb/9874/sync/i.gif?partnerId=1&userKey="+h.getCookie("MFADUser")+"&userId=";b="https://ssum-sec.casalemedia.com/usermatch?s=184665&cb="+encodeURIComponent(b);d.src=b;v.body.appendChild(d)};h.parallel=function(d,b){var a=0,c=d.length;if(!d||!d.length)return b();
for(var f=function(){++a==c&&b()},e=0;e<c;e++)d[e](f)};h.grapeshot=function(d,b,a){var c="https://inskin.gscontxt.net/?url="+encodeURIComponent(b.top.location.href);h.jsonp({url:c,window:b,async:a,callbackName:"parseResponse",timeout:3E3,callback:function(f){var e=[];if(f&&f.channels)for(var g=0;g<f.channels.length;g++)e.push(f.channels[g].name);d(e)},noCleanup:true})}})();(function(){var d=false;F.IntegrationOverride={init:function(){this.telemetry=new F.Telemetry(this);this.dispatchEvent("init");
this._updateParams();this.dispatchEvent("parametersSet");if(this.params.plr_EnableUserMatching&&h.getCookie("MFADUser"))this.params.plr_EnableUserMatching=="init"?h.embedUserMatchingIframe():this.on(this.params.plr_EnableUserMatching,function(){h.embedUserMatchingIframe()});this._ISAPUrl=this.params.plr_UAT?"//staging.inskinad.com/ISAPAdServer/AdS.aspx":"//www.inskinad.com/ISAPAdServer/AdS.aspx";this.telemetry.recordImpression();this._runIntegrationTests()==false&&this._servePassback();var b=this;
this._makeAdCall(function(a){if(b.params.plr_EnableBluekai&&!a&&!b.invalid)h.bluekaiSet({uid:a?a.upcv:"",SectionID:b.params.srv_SectionID,platform:b.meta.platform});if(b.params.srv_Forensiq&&b.params.plr_ForensiqPixel!==false){var c=["http://www.fqtag.com/pixel.cgi?org=5rafuw6aveY8fuPRar5R&p=",b.params.srv_SectionID,"&cmp=",b.params.srv_AdvertIDs,"&fmt=banner&rt=displayImg&sl=1&fq=1&c1=",b.params.srv_Forensiq,"&ty=l"].join("");if(v.location.protocol=="http:"){b.telemetry.startTimer("forensiq-pixel");
h.loadURL(c,function(){Math.random()<0.15&&b.telemetry.sendTimer("forensiq-pixel",1E3)})}}if(a){b.params.plr_CachedISAPResponse=a;b._loadBase(function(){b._bindjQuery();var f;b.params.plr_AdProvider=="MFAD"&&b.$(u).on("message",function(e){e=e.originalEvent;if(!(!e||!e.data||e.data.from!=="ism-rtb-companion"))f=e.source});u.InSkinParams[b.params.plr_InSkinID]=b.params;b.base=new E.Base(b.params.plr_InSkinID);b.base.loadCSS("base.css");b.base.addEventListener("*",function(e){e.name=="ready"&&b.telemetry.recordBaseReady();
if(e.name=="adServed"){b.telemetry.recordAdServed(e);if(b.params.plr_AdProvider=="MFAD"){h.saveFlightIdViewTime(a.flightId);a.body&&h.loadInIframe(a.body)}}if(e.name=="adDwellTime")if(b.params.plr_AdProvider=="MFAD"){var g=0;if(e.data["served-by-mfad"]&&e.data["served-by-mfad"].Expandable)g=e.data["served-by-mfad"].Expandable;if(!b._expandableDwellTime)b._expandableDwellTime=0;var j=Math.floor(b._expandableDwellTime/20);b._expandableDwellTime+=g;n2=Math.floor(b._expandableDwellTime/20);n2>j&&n2<=
15&&InSkin.Util.loadURL(b._responses.MFAD.response.customEvents[60+n2].url)}e.name=="window-load"&&b.telemetry.recordWindowLoad();e.name=="adClick"&&f&&f.postMessage({from:"ism-base"},"*");b.dispatchEvent(e.name,e.data,e.target)});b.base.init()})}else b._servePassback()})},destroy:function(){this.base&&this.base.destroy();delete x.loadedPublisherScripts[this.id]},_runIntegrationTests:function(){var b=true,a,c;for(c in G)if(this.testParams[c]!==false){try{a=G[c].apply(this,this.testParams[c]||[])}catch(f){a=
false}if(a!==true){b=false;this.invalid=true;if(typeof this.params.srv_Invalid=="undefined")this.params.srv_Invalid=true;this.failedTests[c]=a}}return b},_servePassback:function(){if(!d){d=true;var b;if(this.params.passback)b=this.params.passback;else if(typeof u.ISMPassback=="function")b=u.ISMPassback();if(b){b=b.replace(/<\\script>/ig,"<\/script>");var a=this.params.plr_ServePassbackInParent?u:A;this.params.plr_ServePassbackInIframe?setTimeout(function(){var c=a.document.createElement("iframe");
c.style.display="none";var f=a.document.getElementsByTagName("body")[0];f&&f.appendChild(c);if(c=h.getFrameDoc(c,a.document)){f="<!doctype html><html><body>"+b+"</body></html>";c.open();c.write(f);c.close()}},0):h.runJS(b,a)}}},_makeAdCall:function(b){var a=false,c=navigator.userAgent.toLowerCase();if(c.indexOf("msie")!=-1&&parseInt(c.split("msie")[1])==9)a=true;if(this.invalid)a=true;if(this.params.srv_AdvertIDs&&this.params.srv_AdvertIDs!="NETWORK")a=true;if(a)for(a=this.params.plr_AdProviders.length-
1;a>=0;a--)this.params.plr_AdProviders[a]=="MFAD"&&this.params.plr_AdProviders.splice(a,1);if(this.params.srv_AdvertIDs=="NETWORK"&&this.params.plr_AdProviders[0]=="ISAP"&&this.params.plr_AdProviders[1]=="MFAD")this.prioritizeMFAD=true;this._responses={};if(this.invalid)this._makeAdCallToNextProvider(b);else{var f=this;a=[];this.params.plr_EnableBluekai&&a.push(function(e){f.telemetry.startTimer("bluekai");h.bluekaiGet(function(g){f.telemetry.stopTimer("bluekai");f.bluekaiCampaigns=g;g.length&&f._addKeywords(g.map(function(j){return"bk-"+
j}).join(","));e()},A,f.async)});this.params.plr_EnableGrapeshot&&a.push(function(e){f.telemetry.startTimer("grapeshot");h.grapeshot(function(g){f.telemetry.stopTimer("grapeshot");f.grapeshotChannels=g;e()},A,f.async)});h.parallel(a,function(){f._makeAdCallToNextProvider(b)})}},_makeAdCallToNextProvider:function(b){var a=this._nextProviderIndex||0;if(!this.params.plr_AdProviders[a]||this.invalidatedByISAP){var c=null,f=null;if(this.prioritizeMFAD&&this._responses.ISAP&&this._responses.ISAP.hasAd){this.params.plr_AdProvider=
"ISAP";c=this._responses.ISAP.response;f="ISAP"}return b(c,f)}this.params.plr_AdProvider=this.params.plr_AdProviders[a];this._nextProviderIndex=(this._nextProviderIndex||0)+1;this.telemetry.recordAdCall();var e=this;this["_make"+this.params.plr_AdProvider+"AdCall"](function(g){var j=e["_check"+e.params.plr_AdProvider+"Response"](g);e._responses[e.params.plr_AdProvider]={hasAd:j,response:g};if(e.params.plr_AdProvider=="ISAP"&&g&&g.Status!==0)e.invalidatedByISAP=true;e.telemetry.recordAdCallResponse(j?
g:null);if(e.params.plr_AdProvider=="ISAP"&&j){var o=g.PageSkinAd;if(e.prioritizeMFAD&&o.Priority&&o.Priority>3){e._makeAdCallToNextProvider(b);return}if(a==0)if(e.params.mf_flightId||e.params.mf_campaignId){e.params.plr_AdProviders[1]="MFAD";e._makeAdCallToNextProvider(b);return}}j?b(g,e.params.plr_AdProvider):e._makeAdCallToNextProvider(b)})},_makeISAPAdCall:function(b){this._sendRequestToISAP(b)},_sendRequestToISAP:function(b){var a={};if(this.params.plr_DirectAdCall)if(this.params.plr_AdvertID){a.method=
"GetCampaignInformationFromAdvertID";a.vintAdvertID=this.params.plr_AdvertID}else{if(this.params.plr_CreativeID){a.method="GetCampaignInformationFromCreativeID";a.vintCreativeID=this.params.plr_CreativeID}}else{a.method="GetCampaignInformationFromUserData";if(this.params.srv_Forensiq)this.params.srv_Forensiq=Math.floor(Math.random()*1E17);var c=[],f;for(f in this.params)f.match(/^srv_/i)&&c.push(f+"="+this.params[f]);a.vstrCampaignData=c.join("&")}h.extend(a,h.getISAPCookies());h.jsonp({window:A,
url:this._ISAPUrl,async:this.async,data:a,callback:function(e){e&&h.setISAPCookies(e);b&&b(e)}})},_checkISAPResponse:function(b){return!this.invalid&&b&&b.AdType?true:false},_makeMFADAdCall:function(b){var a=this;this._sendRequestToMFAD(function(c){c&&c.user&&h.setCookie("MFADUser",c.user.key,0,"/");var f;if(c&&c.decisions&&c.decisions.ad){f={SectionID:a.params.mf_siteId,AdType:"PageSkin2",PageSkinAd:c.decisions.ad.contents[0].data.customData};f.PageSkinAd.ProductType="PageSkinMF";f.PageSkinAd.CampaignLogID=
"served-by-mfad";c=c.decisions.ad;var e=f.PageSkinAd;e.CampaignID=c.campaignId;e.CreativeID=c.creativeId;e.AdvertID=c.flightId;e.LineItemID=c.adId;f.flightId=c.flightId;f.body=c.contents[0].body||"";f.customEvents=c.events;h.loadURL(c.impressionUrl);if(e.events){var g,j,o,s;for(s in e.events)if(g=s.match(/^(EXPANDABLE_)?EVENT_TAG_(\d+)$/)){j=parseInt(g[2]);o=e.events[s];o.trackers=o.trackers||[];o.trackers.push(c.events[j+(g[1]?40:0)].url);o.silent||o.trackers.push(c.clickUrl)}}e.impressionTrackers=
e.impressionTrackers||{};e.impressionTrackers[0]=e.impressionTrackers[0]||[];e.impressionTrackers[0].push({url:c.events[0].url})}b(f)})},_sendRequestToMFAD:function(b){var a={time:Math.round((new Date).getTime()/1E3),placements:[],url:this.params.plr_HidePageURL?"http://inskinad.com":u.location.href,keywords:this.params.srv_Keywords.split(",")};!this.params.mf_flightId&&!this.params.mf_campaignId&&a.keywords.push("MFNETWORK");var c=h.getCookie("MFADFlightViewTimes");if(c)a.flightViewTimes=JSON.parse(c);
c={divName:"ad",adTypes:[9,163,2163,3006],eventIds:[40]};for(var f=201;f<=240;f++)c.eventIds.push(f);for(f=261;f<=280;f++)c.eventIds.push(f);for(f=281;f<=295;f++)c.eventIds.push(f);for(var e in this.params)if(e.match(/^mf_/i))c[e.replace(/^mf_/,"")]=this.params[e];a.placements.push(c);var g=new XMLHttpRequest;g.open("POST","//mfad.inskinad.com/api/v2",this.async);g.withCredentials=true;g.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");g.onreadystatechange=function(){if(g.readyState==
4)g.status==200?b(JSON.parse(g.responseText)):b(null)};g.send(JSON.stringify(a))},_checkMFADResponse:function(b){return!this.invalid&&b?true:false},_loadBase:function(b){if(this.params.plr_ContentType){var a=false;if(!this.params.plr_UseFullVersion)if(typeof jQuery!="undefined"){var c=jQuery.fn.jquery;if(h.semvercmp(c,"1.4")>=0&&h.semvercmp(c,"1.7.2")<=0)a=true}a=[this.params.BASE_URL+"/js/base/api/",this.params.plr_ContentType.toLowerCase(),a?"-light":"",".js"].join("");h.loadJS(a,null,true,b)}},
_updateParams:function(){var b=this._getAdTagParams(),a;if(b){a=b.srv_Keywords;delete b.srv_Keywords}var c=h.getURLParams(),f;for(f in c)f!="BASE_URL"&&f!="DEBUG"&&!f.match(/^(srv|plr|mf)_/)&&delete c[f];this.params=h.extend({BASE_URL:"https://cdn.inskinad.com/isfe/4.1",srv_ResWidth:screen.width,srv_ResHeight:screen.height,plr_InSkinID:"myInSkin_"+h.random(),plr_AdProviders:["ISAP","MFAD"],plr_EnableGrapeshot:true},b,this.params,c);h.ensureBooleans(this.params,["srv_Invalid","srv_Forensiq","plr_ForensiqPixel",
"plr_DirectAdCall","plr_UAT","plr_UseFullVersion","plr_EnableBluekai","async","plr_ServePassbackInParent","plr_ServePassbackInIframe","plr_HidePageURL","plr_EnableGrapeshot","plr_EnableTelemetryDebug"]);h.ensureIntegers(this.params,["plr_URLKeywords","mf_siteId","mf_flightId","mf_campaignId"]);if(typeof this.params.async!="undefined")this.async=this.params.async;if(typeof this.params.plr_AdProviders=="string")this.params.plr_AdProviders=this.params.plr_AdProviders.split(/\s*,\s*/);a&&this._addKeywords(a);
if(!this.params.srv_Keywords){b=h.getPageKeywords().join(",");this.params.srv_Keywords=b}if(this.params.plr_URLKeywords){b=h.getURLPathKeywords(this.params.plr_URLKeywords).join(",");this._addKeywords(b)}},_getAdTagParams:function(){var b=h.getScriptParams(RegExp(this.id.replace("/","\\/")+"\\.js\\?autoload([^A-Za-z0-9]+)(.*)$"));if(b&&b.id){var a=A[b.id]||u[b.id];a&&h.extend(b,a);delete b.id;this.v2AdTag=true}return b},_addKeywords:function(){var b=Array.prototype.join.call(arguments,",");this.params.srv_Keywords=
h.extendCSV(this.params.srv_Keywords,b)},_addPixel:function(b){if(this.$){b||(b=this.$("body"));b.append('<img src="https://cdn.inskinad.com/isfe/resources/img/1x1.gif" id="ismIMG" width="100%" height="1px" />')}}}})();(function(){function d(a){this.integration=a;this._timers={};this.startTimer("since-load");this._adcalls={};a=navigator.userAgent.toLowerCase();this.isIE9=a.indexOf("msie")!=-1&&parseInt(a.split("msie")[1])==9}F.Telemetry=d;var b=d.prototype;b.setup=function(){};b.send=function(){for(var a=
0;a<arguments.length;a++){var c=arguments[a];c.pubfileId=this.integration.id;c.platform=this.integration.meta.platform||"unknown";c.ua=navigator.userAgent;h[this.isIE9?"jsonp":"post"]({url:"https://mft1.inskinad.com/record",data:c,flatten:true,async:true})}};b.recordCustom=function(a,c){this.send({type:"custom",label:a,value:c||0,url:u.location.href})};b.recordImpression=function(){if(this.integration.params.plr_EnableTelemetryDebug)this.send({type:"impression",tagVersion:this.integration.params.version||
null,url:u.location.href})};b.recordFailedTest=function(a,c){this.send({type:"failed-test",name:a,reason:c})};b.recordAdCall=function(){this._saveAdCallRequest();var a={type:"ad-call",i_delay:this.getTimer("since-load"),tagVersion:this.integration.params.version||null,url:u.location.href,resolution:screen.width+"x"+screen.height},c=this.integration.params;if(c.srv_Keywords)a.a_keywords=c.srv_Keywords;if(c.plr_EnableBluekai&&this.integration.bluekaiCampaigns)a.i_bluekaiTime=this.getTimer("bluekai");
if(c.plr_EnableGrapeshot&&this.integration.grapeshotChannels){a.a_grapeshotChannels=this.integration.grapeshotChannels.join(",");a.i_grapeshotTime=this.getTimer("grapeshot")}if(this.integration.kwScanTime){a.a_kwScanMatches=this.integration.kwScanMatches.join(",");a.i_kwScanTime=this.integration.kwScanTime}switch(c.plr_AdProvider){case "ISAP":a.advertId=c.srv_AdvertIDs||"";break;case "MFAD":a.campaignId=c.mf_campaignId||"";a.flightId=c.mf_flightId||""}this.addAdCallRequestData(a);if(a.b_invalid){c=
[];for(var f in this.integration.failedTests)c.push(f);a.a_failedTests=c.join(",")}this.send(a)};b._saveAdCallRequest=function(){var a=this.integration.params,c=null;switch(a.plr_AdProvider){case "ISAP":c={invalid:this.integration.invalid,direct:a.plr_DirectAdCall&&a.plr_DirectAdCall.toString()=="true",sectionId:a.srv_SectionID||""};break;case "MFAD":c={invalid:this.integration.invalid,siteId:a.mf_siteId||""}}if(c!==null)this._adcalls[a.plr_AdProvider]={request:c}};b.recordAdCallResponse=function(a){this._saveAdCallResponse(a);
a={type:"ad-call-response",i_delay:this.getTimer("since-load")};this.addAdCallRequestData(a);this.addAdCallResponseData(a);if(a.provider=="MFAD"&&this.integration.prioritizeMFAD){var c=this.integration._responses;if(c.ISAP&&c.ISAP.hasAd){a.isapCampaignId=c.ISAP.response.PageSkinAd.CampaignID;a.isapAdvertId=c.ISAP.response.PageSkinAd.AdvertID}}this.integration.invalid||this.send(a)};b._saveAdCallResponse=function(a){var c=this.integration.params.plr_AdProvider;if(this._adcalls[c])if(a&&a.PageSkinAd){this._adcalls[c].hasResponse=
true;var f=this._adcalls[c].response={sectionId:a.SectionID||"",campaignId:a.PageSkinAd.CampaignID,lineItemId:a.PageSkinAd.LineItemID||"",advertId:a.PageSkinAd.AdvertID,creativeId:a.PageSkinAd.CreativeID,productType:a.PageSkinAd.ProductType,vertical:a.PageSkinAd.Vertical||""};if(c=="ISAP"){f.priority=a.PageSkinAd.Priority;f.status=a.Status}}};b.recordBaseReady=function(){if(this.integration.params.plr_EnableTelemetryDebug){var a={type:"base-ready",i_delay:this.getTimer("since-load")};this.addAdCallRequestData(a);
this.addAdCallResponseData(a);this.send(a)}};b.recordAdServed=function(a){a={type:"ad-served",i_delay:this.getTimer("since-load"),b_moat:a.data.moatServed===true};this.addAdCallRequestData(a);this.addAdCallResponseData(a);if(a.provider=="MFAD"&&this.integration.prioritizeMFAD){var c=this.integration._responses;if(c.ISAP&&c.ISAP.hasAd){a.isapCampaignId=c.ISAP.response.PageSkinAd.CampaignID;a.isapAdvertId=c.ISAP.response.PageSkinAd.AdvertID}}this.send(a)};b.recordWindowLoad=function(){if(this.integration.params.plr_EnableTelemetryDebug){var a=
{type:"window-load",i_delay:this.getTimer("since-load")};this.addAdCallRequestData(a);this.addAdCallResponseData(a);this.send(a)}};b.addAdCallRequestData=function(a){var c=this.integration.params.plr_AdProvider;if(this._adcalls[c]&&this._adcalls[c].request){var f=this._adcalls[c].request;a.provider=c;if(f.invalid)a.b_invalid=true;switch(c){case "ISAP":if(f.direct)a.b_direct=true;if(f.sectionId)a.sectionId=f.sectionId;if(f.advertId)a.advertId=f.advertId;break;case "MFAD":if(f.siteId)a.siteId=f.siteId;
if(f.campaignId)a.campaignId=f.campaignId;if(f.flightId)a.flightId=f.flightId}}};b.addAdCallResponseData=function(a){var c=this.integration.params.plr_AdProvider;if(this._adcalls[c]){c=this._adcalls[c].response||{};var f=["vertical"],e;for(e in c){var g;a:{for(g=0;g<f.length;g++)if(f[g]==e){g=g;break a}g=-1}g>=0||(a[e]=c[e])}}};b.startTimer=function(a){a=this._timers[a]||(this._timers[a]={total:0});if(!a.started){a.started=true;a.since=(new Date).getTime()}};b.stopTimer=function(a){var c=this._timers[a]||
null;if(c&&c.started){c.started=false;c.total+=(new Date).getTime()-c.since}return this.getTimer(a)};b.getTimer=function(a){a=this._timers[a]||null;var c=0;if(a){c=a.total;if(a.started)c+=(new Date).getTime()-a.since}return c};b.sendTimer=function(a,c){var f=this.getTimer(a);if(c)f=Math.min(c,f);f&&this.recordCustom("timer-"+a,f)}})();var J=function(){function d(e,g){this.stem=e||"";this.nstem=this.stem.charCodeAt(0);this.sorting=g||d.SORT_DESC;this.prefixCount=this.wordCount=0;this.children=[];this.meta=
[]}function b(e,g,j){if(!e||!g||!j)return null;for(var o,s,w,t;e.length>0;){o=e.charAt(0);s=g.children;w=s.length;for(t=0;t<w;++t)if(o==s[t].stem)break;if(t==w)return null;e=e.substring(1);o=g;g=s[t]}return j(o,t)}function a(e,g){var j=e.nstem,o=g.nstem;return j<o?1:j>o?-1:0}function c(e,g){var j=e.nstem,o=g.nstem;return j>o?1:j<o?-1:0}d.SORT_ASC=1;d.SORT_DESC=2;d.SORT_NONE=4;var f=["stem","nstem","sorting","wordCount","prefixCount","meta"];d.prototype={add:function(e,g){if(e){var j,o=this.sorting,
s=0,w=e.charAt(0),t=this.children,y=t.length;g=g||{};if(!g.word)g.word=e;for(;s<y;++s)if(t[s].stem==w){j=t[s];break}if(!j){++this.prefixCount;j=new d(w,o);if(!o||!t.length||o&d.SORT_NONE)t.push(j);else if(o&d.SORT_DESC){s=y;do if(--s<0){t.unshift(j);break}while(t[s].stem>w);s>=0&&t.splice(s+1,0,j)}else{s=0;--y;do if(++s>y){t.unshift(j);break}while(t[s].stem>w);s<=y&&t.splice(s,0,j)}}j.add(e.substring(1),g)}else{this.meta.push(g);++this.wordCount}},update:function(e,g,j){this.remove(e);this.add(g,
j)},remove:function(e){b(e,this,function(g,j){g.children.remove(j)})},find:function(e){return b(e,this,function(g,j){return g.children[j]})},findPrefix:function(e){return this.find(e)},getChild:function(e){for(var g=0,j=this.children,o=j.length;g<o;++g)if(j[g].stem==e)return j[g];return null},hasChild:function(e){return this.getChild(e)!==null},sort:function(e){if(typeof e=="undefined")e=d.SORT_DESC;if(!(!this.prefixCount||this.sorting===e)){this.sorting=e;if(!(e&d.SORT_NONE)){var g=this.children,
j=g.length-1;for(g.sort(e&d.SORT_ASC?a:c);j>=0;--j)g[j].sort(e)}}},getWords:function(){for(var e=[],g=this.children,j=0,o=g.length;j<o;++j){if(g[j].wordCount)e=e.concat(g[j].meta.map(function(s){return s.word}));e=e.concat(g[j].getWords())}return e},getPrefixCount:function(e){return b(e,this,function(g,j){return g.children[j].prefixCount})||0},getWordCount:function(e){return b(e,this,function(g,j){return g.children[j].wordCount})||0},toString:function(){return"[Trie] '"+this.stem+"': {\n    stem: "+
this.stem+",\n    prefixCount: "+this.prefixCount+",\n    wordCount: "+this.wordCount+",\n    metadata: "+JSON.stringify(this.meta)+",\n    children: [Array]{"+this.children.length+"}\n}"},fromJSON:function(e){f.forEach(function(g){this[g]=e[g]}.bind(this));this.children=e.children.map(function(g){var j=new d;j.fromJSON(g);return j})},toJSON:function(){var e={children:this.children.map(function(g){return g.toJSON()})};f.forEach(function(g){e[g]=this[g]}.bind(this));return e}};return d}();i.attack=
{keyword:"sensitive_content",fullWord:false};i.behead={keyword:"sensitive_content",fullWord:false};i.blast={keyword:"sensitive_content",fullWord:false};i.bomb={keyword:"sensitive_content",fullWord:false};i["child, porn"]={keyword:"sensitive_content",fullWord:false};i["child, sex"]={keyword:"sensitive_content",fullWord:false};i.collided={keyword:"sensitive_content",fullWord:false};i.collision={keyword:"sensitive_content",fullWord:false};i.crash={keyword:"sensitive_content",fullWord:false};i.dead={keyword:"sensitive_content",
fullWord:false};i.disaster={keyword:"sensitive_content",fullWord:false};i["emergency, landing"]={keyword:"sensitive_content",fullWord:false};i.evacuate={keyword:"sensitive_content",fullWord:false};i.evacuation={keyword:"sensitive_content",fullWord:false};i.explosion={keyword:"sensitive_content",fullWord:false};i.explosive={keyword:"sensitive_content",fullWord:false};i.extremist={keyword:"sensitive_content",fullWord:false};i.hostage={keyword:"sensitive_content",fullWord:false};i.incest={keyword:"sensitive_content",
fullWord:false};i.jihad={keyword:"sensitive_content",fullWord:false};i.knife={keyword:"sensitive_content",fullWord:false};i.massacre={keyword:"sensitive_content",fullWord:false};i.murder={keyword:"sensitive_content",fullWord:false};i.paedophile={keyword:"sensitive_content",fullWord:false};i["plane, crash"]={keyword:"sensitive_content",fullWord:false};i.racist={keyword:"sensitive_content",fullWord:false};i.suicide={keyword:"sensitive_content",fullWord:false};i.terror={keyword:"sensitive_content",fullWord:false};
i.weapon={keyword:"sensitive_content",fullWord:false};i.die={keyword:"sensitive_content",fullWord:true};i.died={keyword:"sensitive_content",fullWord:true};i.dies={keyword:"sensitive_content",fullWord:true};i.gun={keyword:"sensitive_content",fullWord:true};i.gunned={keyword:"sensitive_content",fullWord:true};i.guns={keyword:"sensitive_content",fullWord:true};i.isil={keyword:"sensitive_content",fullWord:true};i.isis={keyword:"sensitive_content",fullWord:true};i["islamic state"]={keyword:"sensitive_content",
fullWord:true};i.kill={keyword:"sensitive_content",fullWord:true};i.killed={keyword:"sensitive_content",fullWord:true};i.killer={keyword:"sensitive_content",fullWord:true};i.killers={keyword:"sensitive_content",fullWord:true};i.killing={keyword:"sensitive_content",fullWord:true};i.kills={keyword:"sensitive_content",fullWord:true};i.rape={keyword:"sensitive_content",fullWord:true};i.raped={keyword:"sensitive_content",fullWord:true};i.rapes={keyword:"sensitive_content",fullWord:true};i.raping={keyword:"sensitive_content",
fullWord:true};i.rapist={keyword:"sensitive_content",fullWord:true};i.shoot={keyword:"sensitive_content",fullWord:true};i.shooter={keyword:"sensitive_content",fullWord:true};i.shooters={keyword:"sensitive_content",fullWord:true};i.shooting={keyword:"sensitive_content",fullWord:true};i.shootout={keyword:"sensitive_content",fullWord:true};i.shootouts={keyword:"sensitive_content",fullWord:true};i.shot={keyword:"sensitive_content",fullWord:true};i.stab={keyword:"sensitive_content",fullWord:true};i.stabbed=
{keyword:"sensitive_content",fullWord:true};i.stabber={keyword:"sensitive_content",fullWord:true};i.stabbing={keyword:"sensitive_content",fullWord:true};i.stabbings={keyword:"sensitive_content",fullWord:true};i.stabs={keyword:"sensitive_content",fullWord:true};i.alcohol={keyword:"alcohol",fullWord:false};i.drunk={keyword:"alcohol",fullWord:false};i.vodka={keyword:"alcohol",fullWord:false};i.brawl={keyword:"alcohol",fullWord:false};i.binge={keyword:"alcohol",fullWord:false};i.mas={keyword:"sensitive_mas",
fullWord:true};i["monestary authority"]={keyword:"sensitive_mas",fullWord:true};G.kwfilters=function(){function d(k,m,p){var l=k,n="";m=m.split("");var q=0;q=0;for(var r=[];;){for(q=q;q<m.length;q++)if(l=l.hasChild(m[q])?l.getChild(m[q]):null){n+=m[q];l=l;if(k.getWordCount(n)!=0)if(p)r.push(n);else return[n]}else{l=k;q-=n.length;n=""}if(n=="")return r.length?r:false;else{l=k;q=q-n.length+1;n=""}}}function b(k){var m={invalidate:{trie:new J,hash:{},groups:[]},substitute:{trie:new J,hash:{},groups:[]}},
p,l,n,q,r;for(r in k){n=false;if(typeof k[r]=="object"){if(k[r].from&&k[r].from.getTime()>(new Date).getTime())continue;if(k[r].to&&k[r].to.getTime()<(new Date).getTime())continue;l=k[r].keyword;n=!!k[r].fullWord}else l=k[r];q=l===false?m.invalidate:m.substitute;if(r.indexOf(",")>=0){l={kws:{},keyword:l,keywords:r,fullWord:n};n=q.groups.push(l)-1;for(var B=r.split(/,/),C=0;C<B.length;C++){p=B[C].toLowerCase().replace(/[^a-z0-9 ]/g,"");q.trie.add(p);l.kws[p]=false;q.hash[p]||(q.hash[p]={groups:[]});
q.hash[p].groups.push(n)}}else{p=r.toLowerCase().replace(/[^a-z0-9 ]/g,"");q.trie.add(p);q.hash[p]||(q.hash[p]={});q.hash[p].keyword=l;q.hash[p].fullWord=n}}return m}function a(k,m){if(!k)return false;for(var p=[],l=0;l<k.length;l++){var n=k[l];if(typeof m.hash[n].keyword!="undefined")if(!m.hash[n].fullWord||RegExp("\\b"+n+"\\b","i").test(t)){p.push(n);c(m.hash[n].keyword)}if(m.hash[n].groups)for(var q=0;q<m.hash[n].groups.length;q++){var r=m.groups[m.hash[n].groups[q]];if(!r.fullWord||RegExp("\\b"+
n+"\\b","i").test(t))r.kws[n]=true}}for(l=0;l<m.groups.length;l++){r=m.groups[l];n=true;for(var B in r.kws)n=n&&r.kws[B];if(n){p.push.apply(p,r.keywords.split(","));c(r.keyword)}}return p}function c(k){if(k===false)w=z.params.srv_Invalid=true;else if(!o[k]){o[k]=true;z._addKeywords(k)}}function f(k){if(k&&k.length)for(var m=0;m<k.length;m++)if(!s[k[m]]){s[k[m]]=true;L.push(k[m])}}function e(k){for(var m={text:[],originalText:[]},p=0;p<k.length;p++){if(!y[k[p]]){var l;switch(k[p]){case "url":l=v.location.href;
break;case "title":l=v.title;break;case "keywords":l=h.getPageKeywords("").join(" ");break;case "page":if(z.params.plr_PageScanInclude)l=Array.prototype.reduce.call(v.body.querySelectorAll(z.params.plr_PageScanInclude),function(B,C){return B+C.innerText},"");else if(z.params.plr_PageScanExclude){l=z.params.plr_PageScanExclude.split(/\s*,\s*/);var n=v.body.cloneNode(true);for(p=0;p<l.length;p++)for(var q=n.querySelectorAll(l[p]),r=0;r<q.length;r++)q[r].parentNode.removeChild(q[r]);l=n.innerText}else l=
v.body.innerText}y[k[p]]={originalText:l,text:l.replace(/[^A-Za-z0-9 ]/g,"").toLowerCase()}}m.text.push(y[k[p]].text);m.originalText.push(y[k[p]].originalText)}m.text=m.text.join(" ");m.originalText=m.originalText.join(" ");return m}if(this.params.srv_AdvertIDs!="NETWORK"||this.disableKWFilters)return true;var g,j,o={},s={},w=false,t,y={},z=this,L=z.kwScanMatches=[],M=(new Date).getTime();for(g in x.kwFilters)i[g]=x.kwFilters[g];H.unshift({sources:["keywords","title"],keywords:i});for(var I=0;I<H.length;I++){var K=
H[I];g=b(K.keywords);var D=e(["title","keywords"]);j=D.text;t=D.originalText;j=a(d(g.invalidate.trie,j,true),g.invalidate);f(j);if(w)break;D=e(K.sources);j=D.text;t=D.originalText;j=a(d(g.substitute.trie,j,true),g.substitute);f(j)}z.kwScanTime=(new Date).getTime()-M;return!w}})(window.ismWindow,window);
